apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}
  labels:
    helm.sh/chart: duckula-task-chart-0.1.0
    app.kubernetes.io/name: duckula-task-chart
    app.kubernetes.io/instance: rjzjh
    app.kubernetes.io/version: "3.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: duckula-task-chart
      app.kubernetes.io/instance: rjzjh
  template:
    metadata:
      annotations:
        prometheus.io/path: /
        prometheus.io/port: "2780"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: duckula-task-chart
        app.kubernetes.io/instance: rjzjh
        appname: ${name}
    spec:
      restartPolicy: Always
      hostAliases:
      <#list hosts as host>
      - ip: ${host.ip}
        hostnames: 
       <#list host.hostnames as hostname>
        - ${hostname}
       </#list>
      </#list>
      initContainers:
      - name: pro-data
        image: '${task_image}:${data_version}'
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: data
          mountPath: /data/duckula-data
        - name: userconfig-root
          mountPath: /opt/userconfig
      containers:
        - name: duckula-task-chart
          securityContext:
            {}
          image: '${task_image}:${task_version}'
          imagePullPolicy: IfNotPresent
          #默认使用configmap.properties，注意，不要写错，否则启不来
          env:
          - name: taskid
            value: configmap
          #不能有command否则会覆盖ENTRYPOINT  2113为调试端口，生产环境需要关闭
          #args: ["docker-run.sh","$(taskid)","2723","2113"]
          <#if debug>
          args: ["docker-run.sh","$(taskid)","2723","2113"]
          <#else>
          args: ["docker-run.sh","$(taskid)","2723"]
          </#if>
          ports:
          - name: jmx
            containerPort: 2723
          - name: jmxexporter
            containerPort: 2780
          - name: debug
            containerPort: 2113
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - "/bin/echo 0"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - "/bin/echo 0"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
          - name: data
            mountPath: /data/duckula-data
          - name: userconfig-root
            mountPath: /opt/userconfig
          resources:
            {}
      volumes:
      - name: data
        emptyDir: {}
      - name: userconfig-root
        configMap:
          name: ${configmapname}