package net.wicp.tams.app.duckula.controller.bean.models;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CommonVersionExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table common_version
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table common_version
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table common_version
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_version
	 * @mbg.generated
	 */
	public CommonVersionExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_version
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_version
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_version
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_version
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_version
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_version
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_version
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_version
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_version
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_version
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table common_version
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andMainVersionIsNull() {
			addCriterion("main_version is null");
			return (Criteria) this;
		}

		public Criteria andMainVersionIsNotNull() {
			addCriterion("main_version is not null");
			return (Criteria) this;
		}

		public Criteria andMainVersionEqualTo(String value) {
			addCriterion("main_version =", value, "mainVersion");
			return (Criteria) this;
		}

		public Criteria andMainVersionNotEqualTo(String value) {
			addCriterion("main_version <>", value, "mainVersion");
			return (Criteria) this;
		}

		public Criteria andMainVersionGreaterThan(String value) {
			addCriterion("main_version >", value, "mainVersion");
			return (Criteria) this;
		}

		public Criteria andMainVersionGreaterThanOrEqualTo(String value) {
			addCriterion("main_version >=", value, "mainVersion");
			return (Criteria) this;
		}

		public Criteria andMainVersionLessThan(String value) {
			addCriterion("main_version <", value, "mainVersion");
			return (Criteria) this;
		}

		public Criteria andMainVersionLessThanOrEqualTo(String value) {
			addCriterion("main_version <=", value, "mainVersion");
			return (Criteria) this;
		}

		public Criteria andMainVersionLike(String value) {
			addCriterion("main_version like", value, "mainVersion");
			return (Criteria) this;
		}

		public Criteria andMainVersionNotLike(String value) {
			addCriterion("main_version not like", value, "mainVersion");
			return (Criteria) this;
		}

		public Criteria andMainVersionIn(List<String> values) {
			addCriterion("main_version in", values, "mainVersion");
			return (Criteria) this;
		}

		public Criteria andMainVersionNotIn(List<String> values) {
			addCriterion("main_version not in", values, "mainVersion");
			return (Criteria) this;
		}

		public Criteria andMainVersionBetween(String value1, String value2) {
			addCriterion("main_version between", value1, value2, "mainVersion");
			return (Criteria) this;
		}

		public Criteria andMainVersionNotBetween(String value1, String value2) {
			addCriterion("main_version not between", value1, value2, "mainVersion");
			return (Criteria) this;
		}

		public Criteria andMainPathIsNull() {
			addCriterion("main_path is null");
			return (Criteria) this;
		}

		public Criteria andMainPathIsNotNull() {
			addCriterion("main_path is not null");
			return (Criteria) this;
		}

		public Criteria andMainPathEqualTo(String value) {
			addCriterion("main_path =", value, "mainPath");
			return (Criteria) this;
		}

		public Criteria andMainPathNotEqualTo(String value) {
			addCriterion("main_path <>", value, "mainPath");
			return (Criteria) this;
		}

		public Criteria andMainPathGreaterThan(String value) {
			addCriterion("main_path >", value, "mainPath");
			return (Criteria) this;
		}

		public Criteria andMainPathGreaterThanOrEqualTo(String value) {
			addCriterion("main_path >=", value, "mainPath");
			return (Criteria) this;
		}

		public Criteria andMainPathLessThan(String value) {
			addCriterion("main_path <", value, "mainPath");
			return (Criteria) this;
		}

		public Criteria andMainPathLessThanOrEqualTo(String value) {
			addCriterion("main_path <=", value, "mainPath");
			return (Criteria) this;
		}

		public Criteria andMainPathLike(String value) {
			addCriterion("main_path like", value, "mainPath");
			return (Criteria) this;
		}

		public Criteria andMainPathNotLike(String value) {
			addCriterion("main_path not like", value, "mainPath");
			return (Criteria) this;
		}

		public Criteria andMainPathIn(List<String> values) {
			addCriterion("main_path in", values, "mainPath");
			return (Criteria) this;
		}

		public Criteria andMainPathNotIn(List<String> values) {
			addCriterion("main_path not in", values, "mainPath");
			return (Criteria) this;
		}

		public Criteria andMainPathBetween(String value1, String value2) {
			addCriterion("main_path between", value1, value2, "mainPath");
			return (Criteria) this;
		}

		public Criteria andMainPathNotBetween(String value1, String value2) {
			addCriterion("main_path not between", value1, value2, "mainPath");
			return (Criteria) this;
		}

		public Criteria andDataVersionIsNull() {
			addCriterion("data_version is null");
			return (Criteria) this;
		}

		public Criteria andDataVersionIsNotNull() {
			addCriterion("data_version is not null");
			return (Criteria) this;
		}

		public Criteria andDataVersionEqualTo(String value) {
			addCriterion("data_version =", value, "dataVersion");
			return (Criteria) this;
		}

		public Criteria andDataVersionNotEqualTo(String value) {
			addCriterion("data_version <>", value, "dataVersion");
			return (Criteria) this;
		}

		public Criteria andDataVersionGreaterThan(String value) {
			addCriterion("data_version >", value, "dataVersion");
			return (Criteria) this;
		}

		public Criteria andDataVersionGreaterThanOrEqualTo(String value) {
			addCriterion("data_version >=", value, "dataVersion");
			return (Criteria) this;
		}

		public Criteria andDataVersionLessThan(String value) {
			addCriterion("data_version <", value, "dataVersion");
			return (Criteria) this;
		}

		public Criteria andDataVersionLessThanOrEqualTo(String value) {
			addCriterion("data_version <=", value, "dataVersion");
			return (Criteria) this;
		}

		public Criteria andDataVersionLike(String value) {
			addCriterion("data_version like", value, "dataVersion");
			return (Criteria) this;
		}

		public Criteria andDataVersionNotLike(String value) {
			addCriterion("data_version not like", value, "dataVersion");
			return (Criteria) this;
		}

		public Criteria andDataVersionIn(List<String> values) {
			addCriterion("data_version in", values, "dataVersion");
			return (Criteria) this;
		}

		public Criteria andDataVersionNotIn(List<String> values) {
			addCriterion("data_version not in", values, "dataVersion");
			return (Criteria) this;
		}

		public Criteria andDataVersionBetween(String value1, String value2) {
			addCriterion("data_version between", value1, value2, "dataVersion");
			return (Criteria) this;
		}

		public Criteria andDataVersionNotBetween(String value1, String value2) {
			addCriterion("data_version not between", value1, value2, "dataVersion");
			return (Criteria) this;
		}

		public Criteria andDataPathIsNull() {
			addCriterion("data_path is null");
			return (Criteria) this;
		}

		public Criteria andDataPathIsNotNull() {
			addCriterion("data_path is not null");
			return (Criteria) this;
		}

		public Criteria andDataPathEqualTo(String value) {
			addCriterion("data_path =", value, "dataPath");
			return (Criteria) this;
		}

		public Criteria andDataPathNotEqualTo(String value) {
			addCriterion("data_path <>", value, "dataPath");
			return (Criteria) this;
		}

		public Criteria andDataPathGreaterThan(String value) {
			addCriterion("data_path >", value, "dataPath");
			return (Criteria) this;
		}

		public Criteria andDataPathGreaterThanOrEqualTo(String value) {
			addCriterion("data_path >=", value, "dataPath");
			return (Criteria) this;
		}

		public Criteria andDataPathLessThan(String value) {
			addCriterion("data_path <", value, "dataPath");
			return (Criteria) this;
		}

		public Criteria andDataPathLessThanOrEqualTo(String value) {
			addCriterion("data_path <=", value, "dataPath");
			return (Criteria) this;
		}

		public Criteria andDataPathLike(String value) {
			addCriterion("data_path like", value, "dataPath");
			return (Criteria) this;
		}

		public Criteria andDataPathNotLike(String value) {
			addCriterion("data_path not like", value, "dataPath");
			return (Criteria) this;
		}

		public Criteria andDataPathIn(List<String> values) {
			addCriterion("data_path in", values, "dataPath");
			return (Criteria) this;
		}

		public Criteria andDataPathNotIn(List<String> values) {
			addCriterion("data_path not in", values, "dataPath");
			return (Criteria) this;
		}

		public Criteria andDataPathBetween(String value1, String value2) {
			addCriterion("data_path between", value1, value2, "dataPath");
			return (Criteria) this;
		}

		public Criteria andDataPathNotBetween(String value1, String value2) {
			addCriterion("data_path not between", value1, value2, "dataPath");
			return (Criteria) this;
		}

		public Criteria andImageIsNull() {
			addCriterion("image is null");
			return (Criteria) this;
		}

		public Criteria andImageIsNotNull() {
			addCriterion("image is not null");
			return (Criteria) this;
		}

		public Criteria andImageEqualTo(String value) {
			addCriterion("image =", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageNotEqualTo(String value) {
			addCriterion("image <>", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageGreaterThan(String value) {
			addCriterion("image >", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageGreaterThanOrEqualTo(String value) {
			addCriterion("image >=", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageLessThan(String value) {
			addCriterion("image <", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageLessThanOrEqualTo(String value) {
			addCriterion("image <=", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageLike(String value) {
			addCriterion("image like", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageNotLike(String value) {
			addCriterion("image not like", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageIn(List<String> values) {
			addCriterion("image in", values, "image");
			return (Criteria) this;
		}

		public Criteria andImageNotIn(List<String> values) {
			addCriterion("image not in", values, "image");
			return (Criteria) this;
		}

		public Criteria andImageBetween(String value1, String value2) {
			addCriterion("image between", value1, value2, "image");
			return (Criteria) this;
		}

		public Criteria andImageNotBetween(String value1, String value2) {
			addCriterion("image not between", value1, value2, "image");
			return (Criteria) this;
		}

		public Criteria andAuthorIsNull() {
			addCriterion("author is null");
			return (Criteria) this;
		}

		public Criteria andAuthorIsNotNull() {
			addCriterion("author is not null");
			return (Criteria) this;
		}

		public Criteria andAuthorEqualTo(String value) {
			addCriterion("author =", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotEqualTo(String value) {
			addCriterion("author <>", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorGreaterThan(String value) {
			addCriterion("author >", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorGreaterThanOrEqualTo(String value) {
			addCriterion("author >=", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLessThan(String value) {
			addCriterion("author <", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLessThanOrEqualTo(String value) {
			addCriterion("author <=", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLike(String value) {
			addCriterion("author like", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotLike(String value) {
			addCriterion("author not like", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorIn(List<String> values) {
			addCriterion("author in", values, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotIn(List<String> values) {
			addCriterion("author not in", values, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorBetween(String value1, String value2) {
			addCriterion("author between", value1, value2, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotBetween(String value1, String value2) {
			addCriterion("author not between", value1, value2, "author");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andReadmeIsNull() {
			addCriterion("readme is null");
			return (Criteria) this;
		}

		public Criteria andReadmeIsNotNull() {
			addCriterion("readme is not null");
			return (Criteria) this;
		}

		public Criteria andReadmeEqualTo(String value) {
			addCriterion("readme =", value, "readme");
			return (Criteria) this;
		}

		public Criteria andReadmeNotEqualTo(String value) {
			addCriterion("readme <>", value, "readme");
			return (Criteria) this;
		}

		public Criteria andReadmeGreaterThan(String value) {
			addCriterion("readme >", value, "readme");
			return (Criteria) this;
		}

		public Criteria andReadmeGreaterThanOrEqualTo(String value) {
			addCriterion("readme >=", value, "readme");
			return (Criteria) this;
		}

		public Criteria andReadmeLessThan(String value) {
			addCriterion("readme <", value, "readme");
			return (Criteria) this;
		}

		public Criteria andReadmeLessThanOrEqualTo(String value) {
			addCriterion("readme <=", value, "readme");
			return (Criteria) this;
		}

		public Criteria andReadmeLike(String value) {
			addCriterion("readme like", value, "readme");
			return (Criteria) this;
		}

		public Criteria andReadmeNotLike(String value) {
			addCriterion("readme not like", value, "readme");
			return (Criteria) this;
		}

		public Criteria andReadmeIn(List<String> values) {
			addCriterion("readme in", values, "readme");
			return (Criteria) this;
		}

		public Criteria andReadmeNotIn(List<String> values) {
			addCriterion("readme not in", values, "readme");
			return (Criteria) this;
		}

		public Criteria andReadmeBetween(String value1, String value2) {
			addCriterion("readme between", value1, value2, "readme");
			return (Criteria) this;
		}

		public Criteria andReadmeNotBetween(String value1, String value2) {
			addCriterion("readme not between", value1, value2, "readme");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table common_version
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table common_version
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}