package net.wicp.tams.app.duckula.controller.bean.models;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table common_deploy
 */
public class CommonDeploy {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: 部署类型:  k8s/docker/host This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.deploy
	 * @mbg.generated
	 */
	private String deploy;
	/**
	 * Database Column Remarks: 环境：开发/测试/预发/演示/生产 This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.env
	 * @mbg.generated
	 */
	private String env;
	/**
	 * Database Column Remarks: 名称空间 This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.namespace
	 * @mbg.generated
	 */
	private String namespace;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.url
	 * @mbg.generated
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.token
	 * @mbg.generated
	 */
	private String token;
	/**
	 * Database Column Remarks: user表用户id This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.user_id
	 * @mbg.generated
	 */
	private Long userId;
	/**
	 * Database Column Remarks: 用户名，deploy为host才启作用 This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.host
	 * @mbg.generated
	 */
	private String host;
	/**
	 * Database Column Remarks: SSH端口 This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.port
	 * @mbg.generated
	 */
	private Integer port;
	/**
	 * Database Column Remarks: duckula启动程序用密码，不保留root密码 This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.pwd_duckula
	 * @mbg.generated
	 */
	private String pwdDuckula;
	/**
	 * Database Column Remarks: 需要配置的config,对于"host"类型启作用 This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.hostsconfig
	 * @mbg.generated
	 */
	private String hostsconfig;
	/**
	 * Database Column Remarks: 是否初始化，yes:已初始化  no:未初始化 创建duckula用户，创建环境变量创建目录 This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.is_init
	 * @mbg.generated
	 */
	private String isInit;
	/**
	 * Database Column Remarks: docker类型需要的登陆脚本 This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.docker_login
	 * @mbg.generated
	 */
	private String dockerLogin;
	/**
	 * Database Column Remarks: 是否默认值，yes：是默认某个用户环境的部署机器  no：不是 This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.is_default
	 * @mbg.generated
	 */
	private String isDefault;
	/**
	 * Database Column Remarks: 镜像库的组，如果没有配置就使用阿里云的镜像组 This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.imagegroup
	 * @mbg.generated
	 */
	private String imagegroup;
	/**
	 * Database Column Remarks: 当前的版本,host和docker模式需要升级 This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.version_id
	 * @mbg.generated
	 */
	private Long versionId;
	/**
	 * Database Column Remarks: 备注 This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.remark
	 * @mbg.generated
	 */
	private String remark;
	/**
	 * Database Column Remarks: config配置文件 This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.config
	 * @mbg.generated
	 */
	private String config;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_deploy
	 * @mbg.generated
	 */
	public CommonDeploy(Long id, String name, String deploy, String env, String namespace, String url, String token,
			Long userId, String host, Integer port, String pwdDuckula, String hostsconfig, String isInit,
			String dockerLogin, String isDefault, String imagegroup, Long versionId, String remark) {
		this.id = id;
		this.name = name;
		this.deploy = deploy;
		this.env = env;
		this.namespace = namespace;
		this.url = url;
		this.token = token;
		this.userId = userId;
		this.host = host;
		this.port = port;
		this.pwdDuckula = pwdDuckula;
		this.hostsconfig = hostsconfig;
		this.isInit = isInit;
		this.dockerLogin = dockerLogin;
		this.isDefault = isDefault;
		this.imagegroup = imagegroup;
		this.versionId = versionId;
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_deploy
	 * @mbg.generated
	 */
	public CommonDeploy(Long id, String name, String deploy, String env, String namespace, String url, String token,
			Long userId, String host, Integer port, String pwdDuckula, String hostsconfig, String isInit,
			String dockerLogin, String isDefault, String imagegroup, Long versionId, String remark, String config) {
		this.id = id;
		this.name = name;
		this.deploy = deploy;
		this.env = env;
		this.namespace = namespace;
		this.url = url;
		this.token = token;
		this.userId = userId;
		this.host = host;
		this.port = port;
		this.pwdDuckula = pwdDuckula;
		this.hostsconfig = hostsconfig;
		this.isInit = isInit;
		this.dockerLogin = dockerLogin;
		this.isDefault = isDefault;
		this.imagegroup = imagegroup;
		this.versionId = versionId;
		this.remark = remark;
		this.config = config;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_deploy
	 * @mbg.generated
	 */
	public CommonDeploy() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.id
	 * @return  the value of common_deploy.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.id
	 * @param id  the value for common_deploy.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.name
	 * @return  the value of common_deploy.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.name
	 * @param name  the value for common_deploy.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.deploy
	 * @return  the value of common_deploy.deploy
	 * @mbg.generated
	 */
	public String getDeploy() {
		return deploy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.deploy
	 * @param deploy  the value for common_deploy.deploy
	 * @mbg.generated
	 */
	public void setDeploy(String deploy) {
		this.deploy = deploy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.env
	 * @return  the value of common_deploy.env
	 * @mbg.generated
	 */
	public String getEnv() {
		return env;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.env
	 * @param env  the value for common_deploy.env
	 * @mbg.generated
	 */
	public void setEnv(String env) {
		this.env = env;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.namespace
	 * @return  the value of common_deploy.namespace
	 * @mbg.generated
	 */
	public String getNamespace() {
		return namespace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.namespace
	 * @param namespace  the value for common_deploy.namespace
	 * @mbg.generated
	 */
	public void setNamespace(String namespace) {
		this.namespace = namespace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.url
	 * @return  the value of common_deploy.url
	 * @mbg.generated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.url
	 * @param url  the value for common_deploy.url
	 * @mbg.generated
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.token
	 * @return  the value of common_deploy.token
	 * @mbg.generated
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.token
	 * @param token  the value for common_deploy.token
	 * @mbg.generated
	 */
	public void setToken(String token) {
		this.token = token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.user_id
	 * @return  the value of common_deploy.user_id
	 * @mbg.generated
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.user_id
	 * @param userId  the value for common_deploy.user_id
	 * @mbg.generated
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.host
	 * @return  the value of common_deploy.host
	 * @mbg.generated
	 */
	public String getHost() {
		return host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.host
	 * @param host  the value for common_deploy.host
	 * @mbg.generated
	 */
	public void setHost(String host) {
		this.host = host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.port
	 * @return  the value of common_deploy.port
	 * @mbg.generated
	 */
	public Integer getPort() {
		return port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.port
	 * @param port  the value for common_deploy.port
	 * @mbg.generated
	 */
	public void setPort(Integer port) {
		this.port = port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.pwd_duckula
	 * @return  the value of common_deploy.pwd_duckula
	 * @mbg.generated
	 */
	public String getPwdDuckula() {
		return pwdDuckula;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.pwd_duckula
	 * @param pwdDuckula  the value for common_deploy.pwd_duckula
	 * @mbg.generated
	 */
	public void setPwdDuckula(String pwdDuckula) {
		this.pwdDuckula = pwdDuckula;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.hostsconfig
	 * @return  the value of common_deploy.hostsconfig
	 * @mbg.generated
	 */
	public String getHostsconfig() {
		return hostsconfig;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.hostsconfig
	 * @param hostsconfig  the value for common_deploy.hostsconfig
	 * @mbg.generated
	 */
	public void setHostsconfig(String hostsconfig) {
		this.hostsconfig = hostsconfig;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.is_init
	 * @return  the value of common_deploy.is_init
	 * @mbg.generated
	 */
	public String getIsInit() {
		return isInit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.is_init
	 * @param isInit  the value for common_deploy.is_init
	 * @mbg.generated
	 */
	public void setIsInit(String isInit) {
		this.isInit = isInit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.docker_login
	 * @return  the value of common_deploy.docker_login
	 * @mbg.generated
	 */
	public String getDockerLogin() {
		return dockerLogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.docker_login
	 * @param dockerLogin  the value for common_deploy.docker_login
	 * @mbg.generated
	 */
	public void setDockerLogin(String dockerLogin) {
		this.dockerLogin = dockerLogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.is_default
	 * @return  the value of common_deploy.is_default
	 * @mbg.generated
	 */
	public String getIsDefault() {
		return isDefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.is_default
	 * @param isDefault  the value for common_deploy.is_default
	 * @mbg.generated
	 */
	public void setIsDefault(String isDefault) {
		this.isDefault = isDefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.imagegroup
	 * @return  the value of common_deploy.imagegroup
	 * @mbg.generated
	 */
	public String getImagegroup() {
		return imagegroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.imagegroup
	 * @param imagegroup  the value for common_deploy.imagegroup
	 * @mbg.generated
	 */
	public void setImagegroup(String imagegroup) {
		this.imagegroup = imagegroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.version_id
	 * @return  the value of common_deploy.version_id
	 * @mbg.generated
	 */
	public Long getVersionId() {
		return versionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.version_id
	 * @param versionId  the value for common_deploy.version_id
	 * @mbg.generated
	 */
	public void setVersionId(Long versionId) {
		this.versionId = versionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.remark
	 * @return  the value of common_deploy.remark
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.remark
	 * @param remark  the value for common_deploy.remark
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.config
	 * @return  the value of common_deploy.config
	 * @mbg.generated
	 */
	public String getConfig() {
		return config;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.config
	 * @param config  the value for common_deploy.config
	 * @mbg.generated
	 */
	public void setConfig(String config) {
		this.config = config;
	}
}