package net.wicp.tams.app.duckula.controller.bean.models;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table common_dump
 */
public class CommonDump {

	/**
	 * Database Column Remarks: id This field was generated by MyBatis Generator. This field corresponds to the database column common_dump.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 监听名称 This field was generated by MyBatis Generator. This field corresponds to the database column common_dump.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: 规则 This field was generated by MyBatis Generator. This field corresponds to the database column common_dump.rule
	 * @mbg.generated
	 */
	private String rule;
	/**
	 * Database Column Remarks: duckula监听的版本 This field was generated by MyBatis Generator. This field corresponds to the database column common_dump.version_id
	 * @mbg.generated
	 */
	private Long versionId;
	/**
	 * Database Column Remarks: 部署ID配置 This field was generated by MyBatis Generator. This field corresponds to the database column common_dump.deploy_id
	 * @mbg.generated
	 */
	private Long deployId;
	/**
	 * Database Column Remarks: 用户id This field was generated by MyBatis Generator. This field corresponds to the database column common_dump.user_id
	 * @mbg.generated
	 */
	private Long userId;
	/**
	 * Database Column Remarks: 目的中间件配置 This field was generated by MyBatis Generator. This field corresponds to the database column common_dump.middleware_id
	 * @mbg.generated
	 */
	private Long middlewareId;
	/**
	 * Database Column Remarks: 需要监听的实例配置 This field was generated by MyBatis Generator. This field corresponds to the database column common_dump.instance_id
	 * @mbg.generated
	 */
	private Long instanceId;
	/**
	 * Database Column Remarks: 附加的配置，如自动创建ES索引 This field was generated by MyBatis Generator. This field corresponds to the database column common_dump.attr_config
	 * @mbg.generated
	 */
	private String attrConfig;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_dump
	 * @mbg.generated
	 */
	public CommonDump(Long id, String name, String rule, Long versionId, Long deployId, Long userId, Long middlewareId,
			Long instanceId, String attrConfig) {
		this.id = id;
		this.name = name;
		this.rule = rule;
		this.versionId = versionId;
		this.deployId = deployId;
		this.userId = userId;
		this.middlewareId = middlewareId;
		this.instanceId = instanceId;
		this.attrConfig = attrConfig;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_dump
	 * @mbg.generated
	 */
	public CommonDump() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_dump.id
	 * @return  the value of common_dump.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_dump.id
	 * @param id  the value for common_dump.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_dump.name
	 * @return  the value of common_dump.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_dump.name
	 * @param name  the value for common_dump.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_dump.rule
	 * @return  the value of common_dump.rule
	 * @mbg.generated
	 */
	public String getRule() {
		return rule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_dump.rule
	 * @param rule  the value for common_dump.rule
	 * @mbg.generated
	 */
	public void setRule(String rule) {
		this.rule = rule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_dump.version_id
	 * @return  the value of common_dump.version_id
	 * @mbg.generated
	 */
	public Long getVersionId() {
		return versionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_dump.version_id
	 * @param versionId  the value for common_dump.version_id
	 * @mbg.generated
	 */
	public void setVersionId(Long versionId) {
		this.versionId = versionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_dump.deploy_id
	 * @return  the value of common_dump.deploy_id
	 * @mbg.generated
	 */
	public Long getDeployId() {
		return deployId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_dump.deploy_id
	 * @param deployId  the value for common_dump.deploy_id
	 * @mbg.generated
	 */
	public void setDeployId(Long deployId) {
		this.deployId = deployId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_dump.user_id
	 * @return  the value of common_dump.user_id
	 * @mbg.generated
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_dump.user_id
	 * @param userId  the value for common_dump.user_id
	 * @mbg.generated
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_dump.middleware_id
	 * @return  the value of common_dump.middleware_id
	 * @mbg.generated
	 */
	public Long getMiddlewareId() {
		return middlewareId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_dump.middleware_id
	 * @param middlewareId  the value for common_dump.middleware_id
	 * @mbg.generated
	 */
	public void setMiddlewareId(Long middlewareId) {
		this.middlewareId = middlewareId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_dump.instance_id
	 * @return  the value of common_dump.instance_id
	 * @mbg.generated
	 */
	public Long getInstanceId() {
		return instanceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_dump.instance_id
	 * @param instanceId  the value for common_dump.instance_id
	 * @mbg.generated
	 */
	public void setInstanceId(Long instanceId) {
		this.instanceId = instanceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_dump.attr_config
	 * @return  the value of common_dump.attr_config
	 * @mbg.generated
	 */
	public String getAttrConfig() {
		return attrConfig;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_dump.attr_config
	 * @param attrConfig  the value for common_dump.attr_config
	 * @mbg.generated
	 */
	public void setAttrConfig(String attrConfig) {
		this.attrConfig = attrConfig;
	}
}