package net.wicp.tams.app.duckula.controller.bean.models;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table common_instance
 */
public class CommonInstance {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column common_instance.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 数据库实例名 This field was generated by MyBatis Generator. This field corresponds to the database column common_instance.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column common_instance.host
	 * @mbg.generated
	 */
	private String host;
	/**
	 * Database Column Remarks: 端口 This field was generated by MyBatis Generator. This field corresponds to the database column common_instance.port
	 * @mbg.generated
	 */
	private Integer port;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column common_instance.username
	 * @mbg.generated
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column common_instance.password
	 * @mbg.generated
	 */
	private String password;
	/**
	 * Database Column Remarks: yes:是no:不是 This field was generated by MyBatis Generator. This field corresponds to the database column common_instance.is_drds
	 * @mbg.generated
	 */
	private String isDrds;
	/**
	 * Database Column Remarks: 所属用户 This field was generated by MyBatis Generator. This field corresponds to the database column common_instance.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * Database Column Remarks: 所属公司 This field was generated by MyBatis Generator. This field corresponds to the database column common_instance.com_id
	 * @mbg.generated
	 */
	private String comId;
	/**
	 * Database Column Remarks: 备注 This field was generated by MyBatis Generator. This field corresponds to the database column common_instance.remark
	 * @mbg.generated
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_instance
	 * @mbg.generated
	 */
	public CommonInstance(Long id, String name, String host, Integer port, String username, String password,
			String isDrds, String userId, String comId, String remark) {
		this.id = id;
		this.name = name;
		this.host = host;
		this.port = port;
		this.username = username;
		this.password = password;
		this.isDrds = isDrds;
		this.userId = userId;
		this.comId = comId;
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_instance
	 * @mbg.generated
	 */
	public CommonInstance() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_instance.id
	 * @return  the value of common_instance.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_instance.id
	 * @param id  the value for common_instance.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_instance.name
	 * @return  the value of common_instance.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_instance.name
	 * @param name  the value for common_instance.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_instance.host
	 * @return  the value of common_instance.host
	 * @mbg.generated
	 */
	public String getHost() {
		return host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_instance.host
	 * @param host  the value for common_instance.host
	 * @mbg.generated
	 */
	public void setHost(String host) {
		this.host = host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_instance.port
	 * @return  the value of common_instance.port
	 * @mbg.generated
	 */
	public Integer getPort() {
		return port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_instance.port
	 * @param port  the value for common_instance.port
	 * @mbg.generated
	 */
	public void setPort(Integer port) {
		this.port = port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_instance.username
	 * @return  the value of common_instance.username
	 * @mbg.generated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_instance.username
	 * @param username  the value for common_instance.username
	 * @mbg.generated
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_instance.password
	 * @return  the value of common_instance.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_instance.password
	 * @param password  the value for common_instance.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_instance.is_drds
	 * @return  the value of common_instance.is_drds
	 * @mbg.generated
	 */
	public String getIsDrds() {
		return isDrds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_instance.is_drds
	 * @param isDrds  the value for common_instance.is_drds
	 * @mbg.generated
	 */
	public void setIsDrds(String isDrds) {
		this.isDrds = isDrds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_instance.user_id
	 * @return  the value of common_instance.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_instance.user_id
	 * @param userId  the value for common_instance.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_instance.com_id
	 * @return  the value of common_instance.com_id
	 * @mbg.generated
	 */
	public String getComId() {
		return comId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_instance.com_id
	 * @param comId  the value for common_instance.com_id
	 * @mbg.generated
	 */
	public void setComId(String comId) {
		this.comId = comId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_instance.remark
	 * @return  the value of common_instance.remark
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_instance.remark
	 * @param remark  the value for common_instance.remark
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}