package net.wicp.tams.app.duckula.controller.bean.models;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table common_version
 */
public class CommonVersion {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column common_version.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 主程序版本 This field was generated by MyBatis Generator. This field corresponds to the database column common_version.main_version
	 * @mbg.generated
	 */
	private String mainVersion;
	/**
	 * Database Column Remarks: 主程序存储路径 This field was generated by MyBatis Generator. This field corresponds to the database column common_version.main_path
	 * @mbg.generated
	 */
	private String mainPath;
	/**
	 * Database Column Remarks: 数据版本 This field was generated by MyBatis Generator. This field corresponds to the database column common_version.data_version
	 * @mbg.generated
	 */
	private String dataVersion;
	/**
	 * Database Column Remarks: 数据存储路径 This field was generated by MyBatis Generator. This field corresponds to the database column common_version.data_path
	 * @mbg.generated
	 */
	private String dataPath;
	/**
	 * Database Column Remarks: 镜像库的组，如果没有配置就使用阿里云的镜像组 This field was generated by MyBatis Generator. This field corresponds to the database column common_version.image_group
	 * @mbg.generated
	 */
	private String imageGroup;
	/**
	 * Database Column Remarks: 作者 This field was generated by MyBatis Generator. This field corresponds to the database column common_version.author
	 * @mbg.generated
	 */
	private String author;
	/**
	 * Database Column Remarks: 升级时间 This field was generated by MyBatis Generator. This field corresponds to the database column common_version.update_time
	 * @mbg.generated
	 */
	private Date updateTime;
	/**
	 * Database Column Remarks: 更新说明 This field was generated by MyBatis Generator. This field corresponds to the database column common_version.readme
	 * @mbg.generated
	 */
	private String readme;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_version
	 * @mbg.generated
	 */
	public CommonVersion(Long id, String mainVersion, String mainPath, String dataVersion, String dataPath,
			String imageGroup, String author, Date updateTime, String readme) {
		this.id = id;
		this.mainVersion = mainVersion;
		this.mainPath = mainPath;
		this.dataVersion = dataVersion;
		this.dataPath = dataPath;
		this.imageGroup = imageGroup;
		this.author = author;
		this.updateTime = updateTime;
		this.readme = readme;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_version
	 * @mbg.generated
	 */
	public CommonVersion() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_version.id
	 * @return  the value of common_version.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_version.id
	 * @param id  the value for common_version.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_version.main_version
	 * @return  the value of common_version.main_version
	 * @mbg.generated
	 */
	public String getMainVersion() {
		return mainVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_version.main_version
	 * @param mainVersion  the value for common_version.main_version
	 * @mbg.generated
	 */
	public void setMainVersion(String mainVersion) {
		this.mainVersion = mainVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_version.main_path
	 * @return  the value of common_version.main_path
	 * @mbg.generated
	 */
	public String getMainPath() {
		return mainPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_version.main_path
	 * @param mainPath  the value for common_version.main_path
	 * @mbg.generated
	 */
	public void setMainPath(String mainPath) {
		this.mainPath = mainPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_version.data_version
	 * @return  the value of common_version.data_version
	 * @mbg.generated
	 */
	public String getDataVersion() {
		return dataVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_version.data_version
	 * @param dataVersion  the value for common_version.data_version
	 * @mbg.generated
	 */
	public void setDataVersion(String dataVersion) {
		this.dataVersion = dataVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_version.data_path
	 * @return  the value of common_version.data_path
	 * @mbg.generated
	 */
	public String getDataPath() {
		return dataPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_version.data_path
	 * @param dataPath  the value for common_version.data_path
	 * @mbg.generated
	 */
	public void setDataPath(String dataPath) {
		this.dataPath = dataPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_version.image_group
	 * @return  the value of common_version.image_group
	 * @mbg.generated
	 */
	public String getImageGroup() {
		return imageGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_version.image_group
	 * @param imageGroup  the value for common_version.image_group
	 * @mbg.generated
	 */
	public void setImageGroup(String imageGroup) {
		this.imageGroup = imageGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_version.author
	 * @return  the value of common_version.author
	 * @mbg.generated
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_version.author
	 * @param author  the value for common_version.author
	 * @mbg.generated
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_version.update_time
	 * @return  the value of common_version.update_time
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_version.update_time
	 * @param updateTime  the value for common_version.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_version.readme
	 * @return  the value of common_version.readme
	 * @mbg.generated
	 */
	public String getReadme() {
		return readme;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_version.readme
	 * @param readme  the value for common_version.readme
	 * @mbg.generated
	 */
	public void setReadme(String readme) {
		this.readme = readme;
	}
}