package net.wicp.tams.app.duckula.controller.bean.models;

import java.util.ArrayList;
import java.util.List;

public class CommonMiddlewareExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table common_middleware
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table common_middleware
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table common_middleware
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_middleware
	 * @mbg.generated
	 */
	public CommonMiddlewareExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_middleware
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_middleware
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_middleware
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_middleware
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_middleware
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_middleware
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_middleware
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_middleware
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_middleware
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_middleware
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table common_middleware
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andMiddlewareTypeIsNull() {
			addCriterion("middleware_type is null");
			return (Criteria) this;
		}

		public Criteria andMiddlewareTypeIsNotNull() {
			addCriterion("middleware_type is not null");
			return (Criteria) this;
		}

		public Criteria andMiddlewareTypeEqualTo(String value) {
			addCriterion("middleware_type =", value, "middlewareType");
			return (Criteria) this;
		}

		public Criteria andMiddlewareTypeNotEqualTo(String value) {
			addCriterion("middleware_type <>", value, "middlewareType");
			return (Criteria) this;
		}

		public Criteria andMiddlewareTypeGreaterThan(String value) {
			addCriterion("middleware_type >", value, "middlewareType");
			return (Criteria) this;
		}

		public Criteria andMiddlewareTypeGreaterThanOrEqualTo(String value) {
			addCriterion("middleware_type >=", value, "middlewareType");
			return (Criteria) this;
		}

		public Criteria andMiddlewareTypeLessThan(String value) {
			addCriterion("middleware_type <", value, "middlewareType");
			return (Criteria) this;
		}

		public Criteria andMiddlewareTypeLessThanOrEqualTo(String value) {
			addCriterion("middleware_type <=", value, "middlewareType");
			return (Criteria) this;
		}

		public Criteria andMiddlewareTypeLike(String value) {
			addCriterion("middleware_type like", value, "middlewareType");
			return (Criteria) this;
		}

		public Criteria andMiddlewareTypeNotLike(String value) {
			addCriterion("middleware_type not like", value, "middlewareType");
			return (Criteria) this;
		}

		public Criteria andMiddlewareTypeIn(List<String> values) {
			addCriterion("middleware_type in", values, "middlewareType");
			return (Criteria) this;
		}

		public Criteria andMiddlewareTypeNotIn(List<String> values) {
			addCriterion("middleware_type not in", values, "middlewareType");
			return (Criteria) this;
		}

		public Criteria andMiddlewareTypeBetween(String value1, String value2) {
			addCriterion("middleware_type between", value1, value2, "middlewareType");
			return (Criteria) this;
		}

		public Criteria andMiddlewareTypeNotBetween(String value1, String value2) {
			addCriterion("middleware_type not between", value1, value2, "middlewareType");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("version is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("version is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(String value) {
			addCriterion("version =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(String value) {
			addCriterion("version <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(String value) {
			addCriterion("version >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(String value) {
			addCriterion("version >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(String value) {
			addCriterion("version <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(String value) {
			addCriterion("version <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLike(String value) {
			addCriterion("version like", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotLike(String value) {
			addCriterion("version not like", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<String> values) {
			addCriterion("version in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<String> values) {
			addCriterion("version not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(String value1, String value2) {
			addCriterion("version between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(String value1, String value2) {
			addCriterion("version not between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andComIdIsNull() {
			addCriterion("com_id is null");
			return (Criteria) this;
		}

		public Criteria andComIdIsNotNull() {
			addCriterion("com_id is not null");
			return (Criteria) this;
		}

		public Criteria andComIdEqualTo(String value) {
			addCriterion("com_id =", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdNotEqualTo(String value) {
			addCriterion("com_id <>", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdGreaterThan(String value) {
			addCriterion("com_id >", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdGreaterThanOrEqualTo(String value) {
			addCriterion("com_id >=", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdLessThan(String value) {
			addCriterion("com_id <", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdLessThanOrEqualTo(String value) {
			addCriterion("com_id <=", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdLike(String value) {
			addCriterion("com_id like", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdNotLike(String value) {
			addCriterion("com_id not like", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdIn(List<String> values) {
			addCriterion("com_id in", values, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdNotIn(List<String> values) {
			addCriterion("com_id not in", values, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdBetween(String value1, String value2) {
			addCriterion("com_id between", value1, value2, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdNotBetween(String value1, String value2) {
			addCriterion("com_id not between", value1, value2, "comId");
			return (Criteria) this;
		}

		public Criteria andHostIsNull() {
			addCriterion("host is null");
			return (Criteria) this;
		}

		public Criteria andHostIsNotNull() {
			addCriterion("host is not null");
			return (Criteria) this;
		}

		public Criteria andHostEqualTo(String value) {
			addCriterion("host =", value, "host");
			return (Criteria) this;
		}

		public Criteria andHostNotEqualTo(String value) {
			addCriterion("host <>", value, "host");
			return (Criteria) this;
		}

		public Criteria andHostGreaterThan(String value) {
			addCriterion("host >", value, "host");
			return (Criteria) this;
		}

		public Criteria andHostGreaterThanOrEqualTo(String value) {
			addCriterion("host >=", value, "host");
			return (Criteria) this;
		}

		public Criteria andHostLessThan(String value) {
			addCriterion("host <", value, "host");
			return (Criteria) this;
		}

		public Criteria andHostLessThanOrEqualTo(String value) {
			addCriterion("host <=", value, "host");
			return (Criteria) this;
		}

		public Criteria andHostLike(String value) {
			addCriterion("host like", value, "host");
			return (Criteria) this;
		}

		public Criteria andHostNotLike(String value) {
			addCriterion("host not like", value, "host");
			return (Criteria) this;
		}

		public Criteria andHostIn(List<String> values) {
			addCriterion("host in", values, "host");
			return (Criteria) this;
		}

		public Criteria andHostNotIn(List<String> values) {
			addCriterion("host not in", values, "host");
			return (Criteria) this;
		}

		public Criteria andHostBetween(String value1, String value2) {
			addCriterion("host between", value1, value2, "host");
			return (Criteria) this;
		}

		public Criteria andHostNotBetween(String value1, String value2) {
			addCriterion("host not between", value1, value2, "host");
			return (Criteria) this;
		}

		public Criteria andPortIsNull() {
			addCriterion("port is null");
			return (Criteria) this;
		}

		public Criteria andPortIsNotNull() {
			addCriterion("port is not null");
			return (Criteria) this;
		}

		public Criteria andPortEqualTo(Integer value) {
			addCriterion("port =", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortNotEqualTo(Integer value) {
			addCriterion("port <>", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortGreaterThan(Integer value) {
			addCriterion("port >", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortGreaterThanOrEqualTo(Integer value) {
			addCriterion("port >=", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortLessThan(Integer value) {
			addCriterion("port <", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortLessThanOrEqualTo(Integer value) {
			addCriterion("port <=", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortIn(List<Integer> values) {
			addCriterion("port in", values, "port");
			return (Criteria) this;
		}

		public Criteria andPortNotIn(List<Integer> values) {
			addCriterion("port not in", values, "port");
			return (Criteria) this;
		}

		public Criteria andPortBetween(Integer value1, Integer value2) {
			addCriterion("port between", value1, value2, "port");
			return (Criteria) this;
		}

		public Criteria andPortNotBetween(Integer value1, Integer value2) {
			addCriterion("port not between", value1, value2, "port");
			return (Criteria) this;
		}

		public Criteria andPort2IsNull() {
			addCriterion("port2 is null");
			return (Criteria) this;
		}

		public Criteria andPort2IsNotNull() {
			addCriterion("port2 is not null");
			return (Criteria) this;
		}

		public Criteria andPort2EqualTo(Integer value) {
			addCriterion("port2 =", value, "port2");
			return (Criteria) this;
		}

		public Criteria andPort2NotEqualTo(Integer value) {
			addCriterion("port2 <>", value, "port2");
			return (Criteria) this;
		}

		public Criteria andPort2GreaterThan(Integer value) {
			addCriterion("port2 >", value, "port2");
			return (Criteria) this;
		}

		public Criteria andPort2GreaterThanOrEqualTo(Integer value) {
			addCriterion("port2 >=", value, "port2");
			return (Criteria) this;
		}

		public Criteria andPort2LessThan(Integer value) {
			addCriterion("port2 <", value, "port2");
			return (Criteria) this;
		}

		public Criteria andPort2LessThanOrEqualTo(Integer value) {
			addCriterion("port2 <=", value, "port2");
			return (Criteria) this;
		}

		public Criteria andPort2In(List<Integer> values) {
			addCriterion("port2 in", values, "port2");
			return (Criteria) this;
		}

		public Criteria andPort2NotIn(List<Integer> values) {
			addCriterion("port2 not in", values, "port2");
			return (Criteria) this;
		}

		public Criteria andPort2Between(Integer value1, Integer value2) {
			addCriterion("port2 between", value1, value2, "port2");
			return (Criteria) this;
		}

		public Criteria andPort2NotBetween(Integer value1, Integer value2) {
			addCriterion("port2 not between", value1, value2, "port2");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("username is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("username is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("username =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("username <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("username >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("username >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("username <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("username <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("username like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("username not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("username in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("username not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("username between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("username not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andHostsconfigIsNull() {
			addCriterion("hostsconfig is null");
			return (Criteria) this;
		}

		public Criteria andHostsconfigIsNotNull() {
			addCriterion("hostsconfig is not null");
			return (Criteria) this;
		}

		public Criteria andHostsconfigEqualTo(String value) {
			addCriterion("hostsconfig =", value, "hostsconfig");
			return (Criteria) this;
		}

		public Criteria andHostsconfigNotEqualTo(String value) {
			addCriterion("hostsconfig <>", value, "hostsconfig");
			return (Criteria) this;
		}

		public Criteria andHostsconfigGreaterThan(String value) {
			addCriterion("hostsconfig >", value, "hostsconfig");
			return (Criteria) this;
		}

		public Criteria andHostsconfigGreaterThanOrEqualTo(String value) {
			addCriterion("hostsconfig >=", value, "hostsconfig");
			return (Criteria) this;
		}

		public Criteria andHostsconfigLessThan(String value) {
			addCriterion("hostsconfig <", value, "hostsconfig");
			return (Criteria) this;
		}

		public Criteria andHostsconfigLessThanOrEqualTo(String value) {
			addCriterion("hostsconfig <=", value, "hostsconfig");
			return (Criteria) this;
		}

		public Criteria andHostsconfigLike(String value) {
			addCriterion("hostsconfig like", value, "hostsconfig");
			return (Criteria) this;
		}

		public Criteria andHostsconfigNotLike(String value) {
			addCriterion("hostsconfig not like", value, "hostsconfig");
			return (Criteria) this;
		}

		public Criteria andHostsconfigIn(List<String> values) {
			addCriterion("hostsconfig in", values, "hostsconfig");
			return (Criteria) this;
		}

		public Criteria andHostsconfigNotIn(List<String> values) {
			addCriterion("hostsconfig not in", values, "hostsconfig");
			return (Criteria) this;
		}

		public Criteria andHostsconfigBetween(String value1, String value2) {
			addCriterion("hostsconfig between", value1, value2, "hostsconfig");
			return (Criteria) this;
		}

		public Criteria andHostsconfigNotBetween(String value1, String value2) {
			addCriterion("hostsconfig not between", value1, value2, "hostsconfig");
			return (Criteria) this;
		}

		public Criteria andOptIsNull() {
			addCriterion("opt is null");
			return (Criteria) this;
		}

		public Criteria andOptIsNotNull() {
			addCriterion("opt is not null");
			return (Criteria) this;
		}

		public Criteria andOptEqualTo(String value) {
			addCriterion("opt =", value, "opt");
			return (Criteria) this;
		}

		public Criteria andOptNotEqualTo(String value) {
			addCriterion("opt <>", value, "opt");
			return (Criteria) this;
		}

		public Criteria andOptGreaterThan(String value) {
			addCriterion("opt >", value, "opt");
			return (Criteria) this;
		}

		public Criteria andOptGreaterThanOrEqualTo(String value) {
			addCriterion("opt >=", value, "opt");
			return (Criteria) this;
		}

		public Criteria andOptLessThan(String value) {
			addCriterion("opt <", value, "opt");
			return (Criteria) this;
		}

		public Criteria andOptLessThanOrEqualTo(String value) {
			addCriterion("opt <=", value, "opt");
			return (Criteria) this;
		}

		public Criteria andOptLike(String value) {
			addCriterion("opt like", value, "opt");
			return (Criteria) this;
		}

		public Criteria andOptNotLike(String value) {
			addCriterion("opt not like", value, "opt");
			return (Criteria) this;
		}

		public Criteria andOptIn(List<String> values) {
			addCriterion("opt in", values, "opt");
			return (Criteria) this;
		}

		public Criteria andOptNotIn(List<String> values) {
			addCriterion("opt not in", values, "opt");
			return (Criteria) this;
		}

		public Criteria andOptBetween(String value1, String value2) {
			addCriterion("opt between", value1, value2, "opt");
			return (Criteria) this;
		}

		public Criteria andOptNotBetween(String value1, String value2) {
			addCriterion("opt not between", value1, value2, "opt");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table common_middleware
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table common_middleware
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}