package net.wicp.tams.app.duckula.controller.bean.models;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table common_checkpoint
 */
public class CommonCheckpoint {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column common_checkpoint.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: checkpointName This field was generated by MyBatis Generator. This field corresponds to the database column common_checkpoint.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: 检查点类型 This field was generated by MyBatis Generator. This field corresponds to the database column common_checkpoint.checkpoint_type
	 * @mbg.generated
	 */
	private String checkpointType;
	/**
	 * Database Column Remarks: 检查点主机 This field was generated by MyBatis Generator. This field corresponds to the database column common_checkpoint.host
	 * @mbg.generated
	 */
	private String host;
	/**
	 * Database Column Remarks: 端口 This field was generated by MyBatis Generator. This field corresponds to the database column common_checkpoint.port
	 * @mbg.generated
	 */
	private Integer port;
	/**
	 * Database Column Remarks: 检查点使用的数据库，不填为tams This field was generated by MyBatis Generator. This field corresponds to the database column common_checkpoint.default_db
	 * @mbg.generated
	 */
	private String defaultDb;
	/**
	 * Database Column Remarks: 登陆用户名 This field was generated by MyBatis Generator. This field corresponds to the database column common_checkpoint.username
	 * @mbg.generated
	 */
	private String username;
	/**
	 * Database Column Remarks: 登陆密码 This field was generated by MyBatis Generator. This field corresponds to the database column common_checkpoint.password
	 * @mbg.generated
	 */
	private String password;
	/**
	 * Database Column Remarks: 所属用户 This field was generated by MyBatis Generator. This field corresponds to the database column common_checkpoint.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * Database Column Remarks: 所属公司 This field was generated by MyBatis Generator. This field corresponds to the database column common_checkpoint.com_id
	 * @mbg.generated
	 */
	private String comId;
	/**
	 * Database Column Remarks: 备注 This field was generated by MyBatis Generator. This field corresponds to the database column common_checkpoint.remark
	 * @mbg.generated
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_checkpoint
	 * @mbg.generated
	 */
	public CommonCheckpoint(Long id, String name, String checkpointType, String host, Integer port, String defaultDb,
			String username, String password, String userId, String comId, String remark) {
		this.id = id;
		this.name = name;
		this.checkpointType = checkpointType;
		this.host = host;
		this.port = port;
		this.defaultDb = defaultDb;
		this.username = username;
		this.password = password;
		this.userId = userId;
		this.comId = comId;
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_checkpoint
	 * @mbg.generated
	 */
	public CommonCheckpoint() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_checkpoint.id
	 * @return  the value of common_checkpoint.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_checkpoint.id
	 * @param id  the value for common_checkpoint.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_checkpoint.name
	 * @return  the value of common_checkpoint.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_checkpoint.name
	 * @param name  the value for common_checkpoint.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_checkpoint.checkpoint_type
	 * @return  the value of common_checkpoint.checkpoint_type
	 * @mbg.generated
	 */
	public String getCheckpointType() {
		return checkpointType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_checkpoint.checkpoint_type
	 * @param checkpointType  the value for common_checkpoint.checkpoint_type
	 * @mbg.generated
	 */
	public void setCheckpointType(String checkpointType) {
		this.checkpointType = checkpointType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_checkpoint.host
	 * @return  the value of common_checkpoint.host
	 * @mbg.generated
	 */
	public String getHost() {
		return host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_checkpoint.host
	 * @param host  the value for common_checkpoint.host
	 * @mbg.generated
	 */
	public void setHost(String host) {
		this.host = host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_checkpoint.port
	 * @return  the value of common_checkpoint.port
	 * @mbg.generated
	 */
	public Integer getPort() {
		return port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_checkpoint.port
	 * @param port  the value for common_checkpoint.port
	 * @mbg.generated
	 */
	public void setPort(Integer port) {
		this.port = port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_checkpoint.default_db
	 * @return  the value of common_checkpoint.default_db
	 * @mbg.generated
	 */
	public String getDefaultDb() {
		return defaultDb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_checkpoint.default_db
	 * @param defaultDb  the value for common_checkpoint.default_db
	 * @mbg.generated
	 */
	public void setDefaultDb(String defaultDb) {
		this.defaultDb = defaultDb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_checkpoint.username
	 * @return  the value of common_checkpoint.username
	 * @mbg.generated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_checkpoint.username
	 * @param username  the value for common_checkpoint.username
	 * @mbg.generated
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_checkpoint.password
	 * @return  the value of common_checkpoint.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_checkpoint.password
	 * @param password  the value for common_checkpoint.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_checkpoint.user_id
	 * @return  the value of common_checkpoint.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_checkpoint.user_id
	 * @param userId  the value for common_checkpoint.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_checkpoint.com_id
	 * @return  the value of common_checkpoint.com_id
	 * @mbg.generated
	 */
	public String getComId() {
		return comId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_checkpoint.com_id
	 * @param comId  the value for common_checkpoint.com_id
	 * @mbg.generated
	 */
	public void setComId(String comId) {
		this.comId = comId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_checkpoint.remark
	 * @return  the value of common_checkpoint.remark
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_checkpoint.remark
	 * @param remark  the value for common_checkpoint.remark
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}