package net.wicp.tams.app.duckula.controller.bean.models;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table common_consumer
 */
public class CommonConsumer {

	/**
	 * Database Column Remarks: id This field was generated by MyBatis Generator. This field corresponds to the database column common_consumer.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: consumer名称 This field was generated by MyBatis Generator. This field corresponds to the database column common_consumer.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: 监听的topic，只能监听一个 This field was generated by MyBatis Generator. This field corresponds to the database column common_consumer.topic
	 * @mbg.generated
	 */
	private String topic;
	/**
	 * Database Column Remarks: 规则 This field was generated by MyBatis Generator. This field corresponds to the database column common_consumer.rule
	 * @mbg.generated
	 */
	private String rule;
	/**
	 * Database Column Remarks: duckula监听的版本 This field was generated by MyBatis Generator. This field corresponds to the database column common_consumer.version_id
	 * @mbg.generated
	 */
	private Long versionId;
	/**
	 * Database Column Remarks: 部署ID配置 This field was generated by MyBatis Generator. This field corresponds to the database column common_consumer.deploy_id
	 * @mbg.generated
	 */
	private Long deployId;
	/**
	 * Database Column Remarks: 用户id This field was generated by MyBatis Generator. This field corresponds to the database column common_consumer.user_id
	 * @mbg.generated
	 */
	private Long userId;
	/**
	 * Database Column Remarks: 要监听的kafka配置 This field was generated by MyBatis Generator. This field corresponds to the database column common_consumer.middleware_kafka_id
	 * @mbg.generated
	 */
	private Long middlewareKafkaId;
	/**
	 * Database Column Remarks: 目的中间件配置 This field was generated by MyBatis Generator. This field corresponds to the database column common_consumer.middleware_id
	 * @mbg.generated
	 */
	private Long middlewareId;
	/**
	 * Database Column Remarks: 幂等时的反查实例 This field was generated by MyBatis Generator. This field corresponds to the database column common_consumer.instance_id
	 * @mbg.generated
	 */
	private Long instanceId;
	/**
	 * Database Column Remarks: 组id,监听组 This field was generated by MyBatis Generator. This field corresponds to the database column common_consumer.group_id
	 * @mbg.generated
	 */
	private Integer groupId;
	/**
	 * Database Column Remarks: 附加的配置 This field was generated by MyBatis Generator. This field corresponds to the database column common_consumer.attr_config
	 * @mbg.generated
	 */
	private String attrConfig;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_consumer
	 * @mbg.generated
	 */
	public CommonConsumer(Long id, String name, String topic, String rule, Long versionId, Long deployId, Long userId,
			Long middlewareKafkaId, Long middlewareId, Long instanceId, Integer groupId, String attrConfig) {
		this.id = id;
		this.name = name;
		this.topic = topic;
		this.rule = rule;
		this.versionId = versionId;
		this.deployId = deployId;
		this.userId = userId;
		this.middlewareKafkaId = middlewareKafkaId;
		this.middlewareId = middlewareId;
		this.instanceId = instanceId;
		this.groupId = groupId;
		this.attrConfig = attrConfig;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_consumer
	 * @mbg.generated
	 */
	public CommonConsumer() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_consumer.id
	 * @return  the value of common_consumer.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_consumer.id
	 * @param id  the value for common_consumer.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_consumer.name
	 * @return  the value of common_consumer.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_consumer.name
	 * @param name  the value for common_consumer.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_consumer.topic
	 * @return  the value of common_consumer.topic
	 * @mbg.generated
	 */
	public String getTopic() {
		return topic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_consumer.topic
	 * @param topic  the value for common_consumer.topic
	 * @mbg.generated
	 */
	public void setTopic(String topic) {
		this.topic = topic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_consumer.rule
	 * @return  the value of common_consumer.rule
	 * @mbg.generated
	 */
	public String getRule() {
		return rule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_consumer.rule
	 * @param rule  the value for common_consumer.rule
	 * @mbg.generated
	 */
	public void setRule(String rule) {
		this.rule = rule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_consumer.version_id
	 * @return  the value of common_consumer.version_id
	 * @mbg.generated
	 */
	public Long getVersionId() {
		return versionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_consumer.version_id
	 * @param versionId  the value for common_consumer.version_id
	 * @mbg.generated
	 */
	public void setVersionId(Long versionId) {
		this.versionId = versionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_consumer.deploy_id
	 * @return  the value of common_consumer.deploy_id
	 * @mbg.generated
	 */
	public Long getDeployId() {
		return deployId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_consumer.deploy_id
	 * @param deployId  the value for common_consumer.deploy_id
	 * @mbg.generated
	 */
	public void setDeployId(Long deployId) {
		this.deployId = deployId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_consumer.user_id
	 * @return  the value of common_consumer.user_id
	 * @mbg.generated
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_consumer.user_id
	 * @param userId  the value for common_consumer.user_id
	 * @mbg.generated
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_consumer.middleware_kafka_id
	 * @return  the value of common_consumer.middleware_kafka_id
	 * @mbg.generated
	 */
	public Long getMiddlewareKafkaId() {
		return middlewareKafkaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_consumer.middleware_kafka_id
	 * @param middlewareKafkaId  the value for common_consumer.middleware_kafka_id
	 * @mbg.generated
	 */
	public void setMiddlewareKafkaId(Long middlewareKafkaId) {
		this.middlewareKafkaId = middlewareKafkaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_consumer.middleware_id
	 * @return  the value of common_consumer.middleware_id
	 * @mbg.generated
	 */
	public Long getMiddlewareId() {
		return middlewareId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_consumer.middleware_id
	 * @param middlewareId  the value for common_consumer.middleware_id
	 * @mbg.generated
	 */
	public void setMiddlewareId(Long middlewareId) {
		this.middlewareId = middlewareId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_consumer.instance_id
	 * @return  the value of common_consumer.instance_id
	 * @mbg.generated
	 */
	public Long getInstanceId() {
		return instanceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_consumer.instance_id
	 * @param instanceId  the value for common_consumer.instance_id
	 * @mbg.generated
	 */
	public void setInstanceId(Long instanceId) {
		this.instanceId = instanceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_consumer.group_id
	 * @return  the value of common_consumer.group_id
	 * @mbg.generated
	 */
	public Integer getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_consumer.group_id
	 * @param groupId  the value for common_consumer.group_id
	 * @mbg.generated
	 */
	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_consumer.attr_config
	 * @return  the value of common_consumer.attr_config
	 * @mbg.generated
	 */
	public String getAttrConfig() {
		return attrConfig;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_consumer.attr_config
	 * @param attrConfig  the value for common_consumer.attr_config
	 * @mbg.generated
	 */
	public void setAttrConfig(String attrConfig) {
		this.attrConfig = attrConfig;
	}
}