package net.wicp.tams.app.duckula.controller.bean.models;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class SysGlobalExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_global
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_global
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_global
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_global
	 * @mbg.generated
	 */
	public SysGlobalExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_global
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_global
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_global
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_global
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_global
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_global
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_global
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_global
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_global
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_global
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_global
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andConfigGlobleIsNull() {
			addCriterion("config_globle is null");
			return (Criteria) this;
		}

		public Criteria andConfigGlobleIsNotNull() {
			addCriterion("config_globle is not null");
			return (Criteria) this;
		}

		public Criteria andConfigGlobleEqualTo(String value) {
			addCriterion("config_globle =", value, "configGloble");
			return (Criteria) this;
		}

		public Criteria andConfigGlobleNotEqualTo(String value) {
			addCriterion("config_globle <>", value, "configGloble");
			return (Criteria) this;
		}

		public Criteria andConfigGlobleGreaterThan(String value) {
			addCriterion("config_globle >", value, "configGloble");
			return (Criteria) this;
		}

		public Criteria andConfigGlobleGreaterThanOrEqualTo(String value) {
			addCriterion("config_globle >=", value, "configGloble");
			return (Criteria) this;
		}

		public Criteria andConfigGlobleLessThan(String value) {
			addCriterion("config_globle <", value, "configGloble");
			return (Criteria) this;
		}

		public Criteria andConfigGlobleLessThanOrEqualTo(String value) {
			addCriterion("config_globle <=", value, "configGloble");
			return (Criteria) this;
		}

		public Criteria andConfigGlobleLike(String value) {
			addCriterion("config_globle like", value, "configGloble");
			return (Criteria) this;
		}

		public Criteria andConfigGlobleNotLike(String value) {
			addCriterion("config_globle not like", value, "configGloble");
			return (Criteria) this;
		}

		public Criteria andConfigGlobleIn(List<String> values) {
			addCriterion("config_globle in", values, "configGloble");
			return (Criteria) this;
		}

		public Criteria andConfigGlobleNotIn(List<String> values) {
			addCriterion("config_globle not in", values, "configGloble");
			return (Criteria) this;
		}

		public Criteria andConfigGlobleBetween(String value1, String value2) {
			addCriterion("config_globle between", value1, value2, "configGloble");
			return (Criteria) this;
		}

		public Criteria andConfigGlobleNotBetween(String value1, String value2) {
			addCriterion("config_globle not between", value1, value2, "configGloble");
			return (Criteria) this;
		}

		public Criteria andLastUsernameIsNull() {
			addCriterion("last_username is null");
			return (Criteria) this;
		}

		public Criteria andLastUsernameIsNotNull() {
			addCriterion("last_username is not null");
			return (Criteria) this;
		}

		public Criteria andLastUsernameEqualTo(String value) {
			addCriterion("last_username =", value, "lastUsername");
			return (Criteria) this;
		}

		public Criteria andLastUsernameNotEqualTo(String value) {
			addCriterion("last_username <>", value, "lastUsername");
			return (Criteria) this;
		}

		public Criteria andLastUsernameGreaterThan(String value) {
			addCriterion("last_username >", value, "lastUsername");
			return (Criteria) this;
		}

		public Criteria andLastUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("last_username >=", value, "lastUsername");
			return (Criteria) this;
		}

		public Criteria andLastUsernameLessThan(String value) {
			addCriterion("last_username <", value, "lastUsername");
			return (Criteria) this;
		}

		public Criteria andLastUsernameLessThanOrEqualTo(String value) {
			addCriterion("last_username <=", value, "lastUsername");
			return (Criteria) this;
		}

		public Criteria andLastUsernameLike(String value) {
			addCriterion("last_username like", value, "lastUsername");
			return (Criteria) this;
		}

		public Criteria andLastUsernameNotLike(String value) {
			addCriterion("last_username not like", value, "lastUsername");
			return (Criteria) this;
		}

		public Criteria andLastUsernameIn(List<String> values) {
			addCriterion("last_username in", values, "lastUsername");
			return (Criteria) this;
		}

		public Criteria andLastUsernameNotIn(List<String> values) {
			addCriterion("last_username not in", values, "lastUsername");
			return (Criteria) this;
		}

		public Criteria andLastUsernameBetween(String value1, String value2) {
			addCriterion("last_username between", value1, value2, "lastUsername");
			return (Criteria) this;
		}

		public Criteria andLastUsernameNotBetween(String value1, String value2) {
			addCriterion("last_username not between", value1, value2, "lastUsername");
			return (Criteria) this;
		}

		public Criteria andLastUpdatetimeIsNull() {
			addCriterion("last_updatetime is null");
			return (Criteria) this;
		}

		public Criteria andLastUpdatetimeIsNotNull() {
			addCriterion("last_updatetime is not null");
			return (Criteria) this;
		}

		public Criteria andLastUpdatetimeEqualTo(Date value) {
			addCriterion("last_updatetime =", value, "lastUpdatetime");
			return (Criteria) this;
		}

		public Criteria andLastUpdatetimeNotEqualTo(Date value) {
			addCriterion("last_updatetime <>", value, "lastUpdatetime");
			return (Criteria) this;
		}

		public Criteria andLastUpdatetimeGreaterThan(Date value) {
			addCriterion("last_updatetime >", value, "lastUpdatetime");
			return (Criteria) this;
		}

		public Criteria andLastUpdatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("last_updatetime >=", value, "lastUpdatetime");
			return (Criteria) this;
		}

		public Criteria andLastUpdatetimeLessThan(Date value) {
			addCriterion("last_updatetime <", value, "lastUpdatetime");
			return (Criteria) this;
		}

		public Criteria andLastUpdatetimeLessThanOrEqualTo(Date value) {
			addCriterion("last_updatetime <=", value, "lastUpdatetime");
			return (Criteria) this;
		}

		public Criteria andLastUpdatetimeIn(List<Date> values) {
			addCriterion("last_updatetime in", values, "lastUpdatetime");
			return (Criteria) this;
		}

		public Criteria andLastUpdatetimeNotIn(List<Date> values) {
			addCriterion("last_updatetime not in", values, "lastUpdatetime");
			return (Criteria) this;
		}

		public Criteria andLastUpdatetimeBetween(Date value1, Date value2) {
			addCriterion("last_updatetime between", value1, value2, "lastUpdatetime");
			return (Criteria) this;
		}

		public Criteria andLastUpdatetimeNotBetween(Date value1, Date value2) {
			addCriterion("last_updatetime not between", value1, value2, "lastUpdatetime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_global
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_global
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}