package net.wicp.tams.app.duckula.controller.bean.models;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_permissions
 */
public class SysPermissions {

	/**
	 * Database Column Remarks: 权限编号 This field was generated by MyBatis Generator. This field corresponds to the database column sys_permissions.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 权限名 This field was generated by MyBatis Generator. This field corresponds to the database column sys_permissions.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: 操作类型，data:数据，url:功能 This field was generated by MyBatis Generator. This field corresponds to the database column sys_permissions.opt_type
	 * @mbg.generated
	 */
	private String optType;
	/**
	 * Database Column Remarks: 数据权限有的模式：all,like,equal,expression This field was generated by MyBatis Generator. This field corresponds to the database column sys_permissions.data_pattern
	 * @mbg.generated
	 */
	private String dataPattern;
	/**
	 * Database Column Remarks: 数据权限的值，跟模式搭配使用 This field was generated by MyBatis Generator. This field corresponds to the database column sys_permissions.data_value
	 * @mbg.generated
	 */
	private String dataValue;
	/**
	 * Database Column Remarks: 功能权限的模式：*:全部地址  pre:前缀模式，regular：正则表达式 This field was generated by MyBatis Generator. This field corresponds to the database column sys_permissions.url_pattern
	 * @mbg.generated
	 */
	private String urlPattern;
	/**
	 * Database Column Remarks: 功能权限用的值 This field was generated by MyBatis Generator. This field corresponds to the database column sys_permissions.url_value
	 * @mbg.generated
	 */
	private String urlValue;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permissions
	 * @mbg.generated
	 */
	public SysPermissions(Long id, String name, String optType, String dataPattern, String dataValue, String urlPattern,
			String urlValue) {
		this.id = id;
		this.name = name;
		this.optType = optType;
		this.dataPattern = dataPattern;
		this.dataValue = dataValue;
		this.urlPattern = urlPattern;
		this.urlValue = urlValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permissions
	 * @mbg.generated
	 */
	public SysPermissions() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permissions.id
	 * @return  the value of sys_permissions.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permissions.id
	 * @param id  the value for sys_permissions.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permissions.name
	 * @return  the value of sys_permissions.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permissions.name
	 * @param name  the value for sys_permissions.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permissions.opt_type
	 * @return  the value of sys_permissions.opt_type
	 * @mbg.generated
	 */
	public String getOptType() {
		return optType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permissions.opt_type
	 * @param optType  the value for sys_permissions.opt_type
	 * @mbg.generated
	 */
	public void setOptType(String optType) {
		this.optType = optType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permissions.data_pattern
	 * @return  the value of sys_permissions.data_pattern
	 * @mbg.generated
	 */
	public String getDataPattern() {
		return dataPattern;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permissions.data_pattern
	 * @param dataPattern  the value for sys_permissions.data_pattern
	 * @mbg.generated
	 */
	public void setDataPattern(String dataPattern) {
		this.dataPattern = dataPattern;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permissions.data_value
	 * @return  the value of sys_permissions.data_value
	 * @mbg.generated
	 */
	public String getDataValue() {
		return dataValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permissions.data_value
	 * @param dataValue  the value for sys_permissions.data_value
	 * @mbg.generated
	 */
	public void setDataValue(String dataValue) {
		this.dataValue = dataValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permissions.url_pattern
	 * @return  the value of sys_permissions.url_pattern
	 * @mbg.generated
	 */
	public String getUrlPattern() {
		return urlPattern;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permissions.url_pattern
	 * @param urlPattern  the value for sys_permissions.url_pattern
	 * @mbg.generated
	 */
	public void setUrlPattern(String urlPattern) {
		this.urlPattern = urlPattern;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permissions.url_value
	 * @return  the value of sys_permissions.url_value
	 * @mbg.generated
	 */
	public String getUrlValue() {
		return urlValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permissions.url_value
	 * @param urlValue  the value for sys_permissions.url_value
	 * @mbg.generated
	 */
	public void setUrlValue(String urlValue) {
		this.urlValue = urlValue;
	}
}