package net.wicp.tams.app.duckula.controller.bean.models;

import java.util.ArrayList;
import java.util.List;

public class SysPermissionsExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_permissions
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_permissions
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_permissions
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permissions
	 * @mbg.generated
	 */
	public SysPermissionsExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permissions
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permissions
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permissions
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permissions
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permissions
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permissions
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permissions
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permissions
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permissions
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permissions
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_permissions
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andOptTypeIsNull() {
			addCriterion("opt_type is null");
			return (Criteria) this;
		}

		public Criteria andOptTypeIsNotNull() {
			addCriterion("opt_type is not null");
			return (Criteria) this;
		}

		public Criteria andOptTypeEqualTo(String value) {
			addCriterion("opt_type =", value, "optType");
			return (Criteria) this;
		}

		public Criteria andOptTypeNotEqualTo(String value) {
			addCriterion("opt_type <>", value, "optType");
			return (Criteria) this;
		}

		public Criteria andOptTypeGreaterThan(String value) {
			addCriterion("opt_type >", value, "optType");
			return (Criteria) this;
		}

		public Criteria andOptTypeGreaterThanOrEqualTo(String value) {
			addCriterion("opt_type >=", value, "optType");
			return (Criteria) this;
		}

		public Criteria andOptTypeLessThan(String value) {
			addCriterion("opt_type <", value, "optType");
			return (Criteria) this;
		}

		public Criteria andOptTypeLessThanOrEqualTo(String value) {
			addCriterion("opt_type <=", value, "optType");
			return (Criteria) this;
		}

		public Criteria andOptTypeLike(String value) {
			addCriterion("opt_type like", value, "optType");
			return (Criteria) this;
		}

		public Criteria andOptTypeNotLike(String value) {
			addCriterion("opt_type not like", value, "optType");
			return (Criteria) this;
		}

		public Criteria andOptTypeIn(List<String> values) {
			addCriterion("opt_type in", values, "optType");
			return (Criteria) this;
		}

		public Criteria andOptTypeNotIn(List<String> values) {
			addCriterion("opt_type not in", values, "optType");
			return (Criteria) this;
		}

		public Criteria andOptTypeBetween(String value1, String value2) {
			addCriterion("opt_type between", value1, value2, "optType");
			return (Criteria) this;
		}

		public Criteria andOptTypeNotBetween(String value1, String value2) {
			addCriterion("opt_type not between", value1, value2, "optType");
			return (Criteria) this;
		}

		public Criteria andDataPatternIsNull() {
			addCriterion("data_pattern is null");
			return (Criteria) this;
		}

		public Criteria andDataPatternIsNotNull() {
			addCriterion("data_pattern is not null");
			return (Criteria) this;
		}

		public Criteria andDataPatternEqualTo(String value) {
			addCriterion("data_pattern =", value, "dataPattern");
			return (Criteria) this;
		}

		public Criteria andDataPatternNotEqualTo(String value) {
			addCriterion("data_pattern <>", value, "dataPattern");
			return (Criteria) this;
		}

		public Criteria andDataPatternGreaterThan(String value) {
			addCriterion("data_pattern >", value, "dataPattern");
			return (Criteria) this;
		}

		public Criteria andDataPatternGreaterThanOrEqualTo(String value) {
			addCriterion("data_pattern >=", value, "dataPattern");
			return (Criteria) this;
		}

		public Criteria andDataPatternLessThan(String value) {
			addCriterion("data_pattern <", value, "dataPattern");
			return (Criteria) this;
		}

		public Criteria andDataPatternLessThanOrEqualTo(String value) {
			addCriterion("data_pattern <=", value, "dataPattern");
			return (Criteria) this;
		}

		public Criteria andDataPatternLike(String value) {
			addCriterion("data_pattern like", value, "dataPattern");
			return (Criteria) this;
		}

		public Criteria andDataPatternNotLike(String value) {
			addCriterion("data_pattern not like", value, "dataPattern");
			return (Criteria) this;
		}

		public Criteria andDataPatternIn(List<String> values) {
			addCriterion("data_pattern in", values, "dataPattern");
			return (Criteria) this;
		}

		public Criteria andDataPatternNotIn(List<String> values) {
			addCriterion("data_pattern not in", values, "dataPattern");
			return (Criteria) this;
		}

		public Criteria andDataPatternBetween(String value1, String value2) {
			addCriterion("data_pattern between", value1, value2, "dataPattern");
			return (Criteria) this;
		}

		public Criteria andDataPatternNotBetween(String value1, String value2) {
			addCriterion("data_pattern not between", value1, value2, "dataPattern");
			return (Criteria) this;
		}

		public Criteria andDataValueIsNull() {
			addCriterion("data_value is null");
			return (Criteria) this;
		}

		public Criteria andDataValueIsNotNull() {
			addCriterion("data_value is not null");
			return (Criteria) this;
		}

		public Criteria andDataValueEqualTo(String value) {
			addCriterion("data_value =", value, "dataValue");
			return (Criteria) this;
		}

		public Criteria andDataValueNotEqualTo(String value) {
			addCriterion("data_value <>", value, "dataValue");
			return (Criteria) this;
		}

		public Criteria andDataValueGreaterThan(String value) {
			addCriterion("data_value >", value, "dataValue");
			return (Criteria) this;
		}

		public Criteria andDataValueGreaterThanOrEqualTo(String value) {
			addCriterion("data_value >=", value, "dataValue");
			return (Criteria) this;
		}

		public Criteria andDataValueLessThan(String value) {
			addCriterion("data_value <", value, "dataValue");
			return (Criteria) this;
		}

		public Criteria andDataValueLessThanOrEqualTo(String value) {
			addCriterion("data_value <=", value, "dataValue");
			return (Criteria) this;
		}

		public Criteria andDataValueLike(String value) {
			addCriterion("data_value like", value, "dataValue");
			return (Criteria) this;
		}

		public Criteria andDataValueNotLike(String value) {
			addCriterion("data_value not like", value, "dataValue");
			return (Criteria) this;
		}

		public Criteria andDataValueIn(List<String> values) {
			addCriterion("data_value in", values, "dataValue");
			return (Criteria) this;
		}

		public Criteria andDataValueNotIn(List<String> values) {
			addCriterion("data_value not in", values, "dataValue");
			return (Criteria) this;
		}

		public Criteria andDataValueBetween(String value1, String value2) {
			addCriterion("data_value between", value1, value2, "dataValue");
			return (Criteria) this;
		}

		public Criteria andDataValueNotBetween(String value1, String value2) {
			addCriterion("data_value not between", value1, value2, "dataValue");
			return (Criteria) this;
		}

		public Criteria andUrlPatternIsNull() {
			addCriterion("url_pattern is null");
			return (Criteria) this;
		}

		public Criteria andUrlPatternIsNotNull() {
			addCriterion("url_pattern is not null");
			return (Criteria) this;
		}

		public Criteria andUrlPatternEqualTo(String value) {
			addCriterion("url_pattern =", value, "urlPattern");
			return (Criteria) this;
		}

		public Criteria andUrlPatternNotEqualTo(String value) {
			addCriterion("url_pattern <>", value, "urlPattern");
			return (Criteria) this;
		}

		public Criteria andUrlPatternGreaterThan(String value) {
			addCriterion("url_pattern >", value, "urlPattern");
			return (Criteria) this;
		}

		public Criteria andUrlPatternGreaterThanOrEqualTo(String value) {
			addCriterion("url_pattern >=", value, "urlPattern");
			return (Criteria) this;
		}

		public Criteria andUrlPatternLessThan(String value) {
			addCriterion("url_pattern <", value, "urlPattern");
			return (Criteria) this;
		}

		public Criteria andUrlPatternLessThanOrEqualTo(String value) {
			addCriterion("url_pattern <=", value, "urlPattern");
			return (Criteria) this;
		}

		public Criteria andUrlPatternLike(String value) {
			addCriterion("url_pattern like", value, "urlPattern");
			return (Criteria) this;
		}

		public Criteria andUrlPatternNotLike(String value) {
			addCriterion("url_pattern not like", value, "urlPattern");
			return (Criteria) this;
		}

		public Criteria andUrlPatternIn(List<String> values) {
			addCriterion("url_pattern in", values, "urlPattern");
			return (Criteria) this;
		}

		public Criteria andUrlPatternNotIn(List<String> values) {
			addCriterion("url_pattern not in", values, "urlPattern");
			return (Criteria) this;
		}

		public Criteria andUrlPatternBetween(String value1, String value2) {
			addCriterion("url_pattern between", value1, value2, "urlPattern");
			return (Criteria) this;
		}

		public Criteria andUrlPatternNotBetween(String value1, String value2) {
			addCriterion("url_pattern not between", value1, value2, "urlPattern");
			return (Criteria) this;
		}

		public Criteria andUrlValueIsNull() {
			addCriterion("url_value is null");
			return (Criteria) this;
		}

		public Criteria andUrlValueIsNotNull() {
			addCriterion("url_value is not null");
			return (Criteria) this;
		}

		public Criteria andUrlValueEqualTo(String value) {
			addCriterion("url_value =", value, "urlValue");
			return (Criteria) this;
		}

		public Criteria andUrlValueNotEqualTo(String value) {
			addCriterion("url_value <>", value, "urlValue");
			return (Criteria) this;
		}

		public Criteria andUrlValueGreaterThan(String value) {
			addCriterion("url_value >", value, "urlValue");
			return (Criteria) this;
		}

		public Criteria andUrlValueGreaterThanOrEqualTo(String value) {
			addCriterion("url_value >=", value, "urlValue");
			return (Criteria) this;
		}

		public Criteria andUrlValueLessThan(String value) {
			addCriterion("url_value <", value, "urlValue");
			return (Criteria) this;
		}

		public Criteria andUrlValueLessThanOrEqualTo(String value) {
			addCriterion("url_value <=", value, "urlValue");
			return (Criteria) this;
		}

		public Criteria andUrlValueLike(String value) {
			addCriterion("url_value like", value, "urlValue");
			return (Criteria) this;
		}

		public Criteria andUrlValueNotLike(String value) {
			addCriterion("url_value not like", value, "urlValue");
			return (Criteria) this;
		}

		public Criteria andUrlValueIn(List<String> values) {
			addCriterion("url_value in", values, "urlValue");
			return (Criteria) this;
		}

		public Criteria andUrlValueNotIn(List<String> values) {
			addCriterion("url_value not in", values, "urlValue");
			return (Criteria) this;
		}

		public Criteria andUrlValueBetween(String value1, String value2) {
			addCriterion("url_value between", value1, value2, "urlValue");
			return (Criteria) this;
		}

		public Criteria andUrlValueNotBetween(String value1, String value2) {
			addCriterion("url_value not between", value1, value2, "urlValue");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_permissions
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_permissions
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}