package net.wicp.tams.app.duckula.controller.bean.models;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_user
 */
public class SysUser {

	/**
	 * Database Column Remarks: 登陆ID This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: username This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.username
	 * @mbg.generated
	 */
	private String username;
	/**
	 * Database Column Remarks: 密码 This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.password
	 * @mbg.generated
	 */
	private String password;
	/**
	 * Database Column Remarks: 盐 This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.salt
	 * @mbg.generated
	 */
	private String salt;
	/**
	 * Database Column Remarks: 邮箱 This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.email
	 * @mbg.generated
	 */
	private String email;
	/**
	 * Database Column Remarks: 手机号 This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.mobile
	 * @mbg.generated
	 */
	private String mobile;
	/**
	 * Database Column Remarks: 状态  0：禁用   1：正常 This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.status
	 * @mbg.generated
	 */
	private Byte status;
	/**
	 * Database Column Remarks: 公司名称 This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.com_name
	 * @mbg.generated
	 */
	private String comName;
	/**
	 * Database Column Remarks: 创建时间 This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * Database Column Remarks: 修改时间 This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.update_time
	 * @mbg.generated
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbg.generated
	 */
	public SysUser(Long id, String username, String password, String salt, String email, String mobile, Byte status,
			String comName, Date createTime, Date updateTime) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.salt = salt;
		this.email = email;
		this.mobile = mobile;
		this.status = status;
		this.comName = comName;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbg.generated
	 */
	public SysUser() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.id
	 * @return  the value of sys_user.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.id
	 * @param id  the value for sys_user.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.username
	 * @return  the value of sys_user.username
	 * @mbg.generated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.username
	 * @param username  the value for sys_user.username
	 * @mbg.generated
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.password
	 * @return  the value of sys_user.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.password
	 * @param password  the value for sys_user.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.salt
	 * @return  the value of sys_user.salt
	 * @mbg.generated
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.salt
	 * @param salt  the value for sys_user.salt
	 * @mbg.generated
	 */
	public void setSalt(String salt) {
		this.salt = salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.email
	 * @return  the value of sys_user.email
	 * @mbg.generated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.email
	 * @param email  the value for sys_user.email
	 * @mbg.generated
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.mobile
	 * @return  the value of sys_user.mobile
	 * @mbg.generated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.mobile
	 * @param mobile  the value for sys_user.mobile
	 * @mbg.generated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.status
	 * @return  the value of sys_user.status
	 * @mbg.generated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.status
	 * @param status  the value for sys_user.status
	 * @mbg.generated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.com_name
	 * @return  the value of sys_user.com_name
	 * @mbg.generated
	 */
	public String getComName() {
		return comName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.com_name
	 * @param comName  the value for sys_user.com_name
	 * @mbg.generated
	 */
	public void setComName(String comName) {
		this.comName = comName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.create_time
	 * @return  the value of sys_user.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.create_time
	 * @param createTime  the value for sys_user.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.update_time
	 * @return  the value of sys_user.update_time
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.update_time
	 * @param updateTime  the value for sys_user.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}