# Default values for duckula3-char.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1


image: registry.cn-hangzhou.aliyuncs.com/rjzjh/duckula
imageOpsTag: ops.3.0.0

nameOverride: ""
fullnameOverride: ""



podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000





resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi



nodeSelector: {}

tolerations: []

affinity: {}
#支持2层目录，暂只用一层就好了
userconfig:
  root:
    duckula-ops.properties: |-
      #es
      spring.datasource.dynamic.primary=master
      spring.datasource.dynamic.strict=false
      spring.datasource.dynamic.datasource.master.url=jdbc:mysql://docker.for.win.localhost:3306/duckula?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      spring.datasource.dynamic.datasource.master.username=root
      spring.datasource.dynamic.datasource.master.password=mysql     
      spring.datasource.dynamic.datasource.master.driver-class-name=com.mysql.jdbc.Driver
      spring.cloud.refresh.refreshable=none
      mybatis-plus.mapper-locations=classpath:mybatis/primary/sqlmap/*.xml
      logging.level.net.wicp.tams.app.duckula.controller.dao=DEBUG 